"""empty message

Revision ID: 2639b77514f9
Revises: f424cb220704
Create Date: 2021-04-23 18:16:56.769486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2639b77514f9'
down_revision = 'f424cb220704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('Bebida', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('Bocadillos', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('DJ', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('Decoracion', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('Ensalada', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('Entrada', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('Plato_Fuerte', sa.String(length=500), nullable=False))
    op.add_column('service', sa.Column('Postre', sa.String(length=500), nullable=False))
    op.drop_column('service', 'decoracion')
    op.drop_column('service', 'dj')
    op.drop_column('service', 'catering_service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('catering_service', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('dj', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('decoracion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('service', 'Postre')
    op.drop_column('service', 'Plato_Fuerte')
    op.drop_column('service', 'Entrada')
    op.drop_column('service', 'Ensalada')
    op.drop_column('service', 'Decoracion')
    op.drop_column('service', 'DJ')
    op.drop_column('service', 'Bocadillos')
    op.drop_column('service', 'Bebida')
    # ### end Alembic commands ###
