"""empty message

Revision ID: 95cf8a116796
Revises: 3f5e5e5759d5
Create Date: 2021-04-20 03:12:35.620160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cf8a116796'
down_revision = '3f5e5e5759d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shop_cart', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.drop_column('shop_cart', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_cart', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('shop_cart', 'cantidad')
    op.drop_table('factura')
    # ### end Alembic commands ###
