"""empty message

Revision ID: f424cb220704
Revises: 95cf8a116796
Create Date: 2021-04-22 13:34:54.371722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f424cb220704'
down_revision = '95cf8a116796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('catering_service', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('decoracion', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('dj', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('stock', sa.Integer(), nullable=True))
    op.drop_constraint('service_description_key', 'service', type_='unique')
    op.drop_column('service', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.create_unique_constraint('service_description_key', 'service', ['description'])
    op.drop_column('service', 'stock')
    op.drop_column('service', 'dj')
    op.drop_column('service', 'decoracion')
    op.drop_column('service', 'catering_service')
    # ### end Alembic commands ###
